[package]
name = "uchat_query"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
diesel-derive-newtype = "2.1.2"
diesel_migrations = { version = "2.3.2", features = ["postgres"] }
password-hash = { version = "0.5.0", features = ["alloc"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
tracing = { version = "0.1.44", features = ["attributes"] }
url = { version = "2.5.8" }
uuid = { version = "1.23.4", features = ["v4", "serde"] }

uchat_domain = { path = "../../shared/domain", features = ["query"] }
uchat_endpoint = { path = "../../shared/endpoint" }

[dependencies.diesel]
features = [
  "postgres",
  "uuid",
  "chrono",
  "serde_json",
  "i-implement-a-third-party-backend-and-opt-into-breaking-changes",
  "postgres_backend",
]
version = "2.3.10"
default-features = false

[dev-dependencies]
dotenvy = "0.15.7"
uchat_crypto = { path = "../crypto" }
